USE DATABASE SALES_DWH_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
    TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        NULL_IF = ('NULL', 'null', '');