USE DATABASE SALES_DWH_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE STAGE METADATA_STAGE
    URL = 's3://sales-metadata-driven-elt/metadata/'
    STORAGE_INTEGRATION = S3_METADATA_INT
    FILE_FORMAT = CSV_FILE_FORMAT;

LIST @METADATA_STAGE;

CREATE OR REPLACE STAGE BRONZE_STAGE
    URL = 's3://sales-data-lake-dev/bronze/'
    STORAGE_INTEGRATION = S3_METADATA_INT
    FILE_FORMAT = CSV_FILE_FORMAT;

LIST @BRONZE_STAGE;
