USE DATABASE SALES_DWH_DEV;
USE SCHEMA SILVER;

-- =========================================================
-- FILE: validate_silver_customer.sql
-- PURPOSE:
-- Validate SILVER.CUSTOMER after SP_LOAD_PIPELINE('LOAD_CUSTOMER')
-- =========================================================

-- 1. Total row count in Silver
SELECT
    'TOTAL_ROW_COUNT' AS CHECK_NAME,
    COUNT(*) AS CHECK_VALUE
FROM SALES_DWH_DEV.SILVER.CUSTOMER;

-- 2. Null check for primary/business key
SELECT
    'NULL_CUSTOMER_ID' AS CHECK_NAME,
    COUNT(*) AS CHECK_VALUE
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE CUSTOMER_ID IS NULL;

-- 3. Duplicate check for CUSTOMER_ID
SELECT
    CUSTOMER_ID,
    COUNT(*) AS DUP_COUNT
FROM SALES_DWH_DEV.SILVER.CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- 4. Distribution of derived CUSTOMER_TYPE
SELECT
    CUSTOMER_TYPE,
    COUNT(*) AS RECORD_COUNT
FROM SALES_DWH_DEV.SILVER.CUSTOMER
GROUP BY CUSTOMER_TYPE
ORDER BY RECORD_COUNT DESC;

-- 5. Check for invalid or null CUSTOMER_TYPE values
SELECT *
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE CUSTOMER_TYPE NOT IN ('PERSON', 'STORE', 'NOT_APPLICABLE', 'INVALID')
   OR CUSTOMER_TYPE IS NULL;

-- 6. Validate CUSTOMER_TYPE derivation logic
SELECT *
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE CUSTOMER_TYPE <>
      CASE
          WHEN PERSON_ID IS NOT NULL AND STORE_ID IS NULL THEN 'PERSON'
          WHEN PERSON_ID IS NULL AND STORE_ID IS NOT NULL THEN 'STORE'
          WHEN PERSON_ID IS NULL AND STORE_ID IS NULL THEN 'NOT_APPLICABLE'
          WHEN PERSON_ID IS NOT NULL AND STORE_ID IS NOT NULL THEN 'INVALID'
          END;

-- 7. Check default handling of TERRITORY_ID
SELECT
    'DEFAULT_TERRITORY_ID_COUNT' AS CHECK_NAME,
    COUNT(*) AS CHECK_VALUE
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE TERRITORY_ID = -1;

-- 8. Check ACCOUNT_NUMBER standardization to uppercase
SELECT *
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE ACCOUNT_NUMBER IS NOT NULL
  AND ACCOUNT_NUMBER <> UPPER(ACCOUNT_NUMBER);

-- 9. Check ROWGUID standardization to lowercase
SELECT *
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE ROWGUID IS NOT NULL
  AND ROWGUID <> LOWER(ROWGUID);

-- 10. Check future MODIFIED_DATE values
SELECT *
FROM SALES_DWH_DEV.SILVER.CUSTOMER
WHERE MODIFIED_DATE > CURRENT_TIMESTAMP();

-- 11. Bronze vs Silver row count comparison
SELECT
    (SELECT COUNT(*) FROM SALES_DWH_DEV.BRONZE.CUSTOMER_RAW) AS BRONZE_ROW_COUNT,
    (SELECT COUNT(*) FROM SALES_DWH_DEV.SILVER.CUSTOMER) AS SILVER_ROW_COUNT;

-- 12. Sample records for manual inspection
SELECT *
FROM SALES_DWH_DEV.SILVER.CUSTOMER
         LIMIT 20;