CREATE DATABASE IF NOT EXISTS SALES_DWH_DEV;

USE DATABASE SALES_DWH_DEV;

CREATE SCHEMA IF NOT EXISTS CONTROL;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

SHOW SCHEMAS IN DATABASE SALES_DWH_DEV;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();