USE DATABASE SALES_DWH_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE PROCEDURE SP_LOAD_PIPELINE(PIPELINE_NAME_ARG STRING)
    RETURNS STRING
    LANGUAGE SQL
AS
$$
DECLARE
    V_SOURCE_TABLE STRING;
    V_TARGET_TABLE STRING;
    V_LOAD_TYPE STRING;
    V_LOAD_MODE STRING;

    V_TARGET_COLUMNS STRING;
    V_SELECT_EXPRESSIONS STRING;
    V_SQL STRING;
BEGIN
    SELECT
        SOURCE_TABLE,
        TARGET_TABLE,
        LOAD_TYPE,
        LOAD_MODE
        INTO
        :V_SOURCE_TABLE,
        :V_TARGET_TABLE,
        :V_LOAD_TYPE,
        :V_LOAD_MODE
    FROM SALES_DWH_DEV.CONTROL.LOAD_CONFIG
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND ACTIVE_FLAG = TRUE;

    SELECT LISTAGG(TARGET_COLUMN, ', ')
                   WITHIN GROUP (ORDER BY COLUMN_SEQUENCE)
        INTO :V_TARGET_COLUMNS
    FROM SALES_DWH_DEV.CONTROL.COLUMN_MAPPING
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND ACTIVE_FLAG = TRUE;

    SELECT LISTAGG(TRANSFORM_EXPRESSION || ' AS ' || TARGET_COLUMN, ', ')
                   WITHIN GROUP (ORDER BY COLUMN_SEQUENCE)
        INTO :V_SELECT_EXPRESSIONS
    FROM SALES_DWH_DEV.CONTROL.COLUMN_MAPPING
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND ACTIVE_FLAG = TRUE;

    IF (V_LOAD_MODE = 'TRUNCATE_INSERT') THEN

        EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TARGET_TABLE;

        V_SQL := 'INSERT INTO ' || V_TARGET_TABLE || ' (' ||
                 V_TARGET_COLUMNS || ') SELECT ' ||
                 V_SELECT_EXPRESSIONS || ' FROM ' || V_SOURCE_TABLE;

        EXECUTE IMMEDIATE V_SQL;

        RETURN 'SUCCESS: PIPELINE ' || PIPELINE_NAME_ARG || ' executed using TRUNCATE_INSERT';

    ELSE
        RETURN 'ERROR: Unsupported LOAD_MODE for V1 -> ' || COALESCE(V_LOAD_MODE, 'NULL');

    END IF;

EXCEPTION
    WHEN OTHER THEN
        RETURN 'FAILED: Pipeline ' || PIPELINE_NAME_ARG || ' | Error: ' || SQLERRM;

END;
$$;