USE DATABASE SALES_DWH_DEV;
USE SCHEMA BRONZE;

-- 1. Total rows
SELECT 'TOTAL_ROWS' AS CHECK_NAME, COUNT(*) AS VALUE
FROM CUSTOMER_RAW;

-- 2. Null CUSTOMERID (critical)
SELECT 'NULL_CUSTOMERID' AS CHECK_NAME, COUNT(*) AS VALUE
FROM CUSTOMER_RAW
WHERE CUSTOMERID IS NULL;

-- 3. Duplicate CUSTOMERID
SELECT CUSTOMERID, COUNT(*) AS DUP_COUNT
FROM CUSTOMER_RAW
GROUP BY CUSTOMERID
HAVING COUNT(*) > 1;

-- 4. PERSONID vs STOREID sanity
SELECT
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN PERSONID IS NOT NULL THEN 1 ELSE 0 END) AS PERSON_COUNT,
    SUM(CASE WHEN STOREID IS NOT NULL THEN 1 ELSE 0 END) AS STORE_COUNT
FROM CUSTOMER_RAW;

-- 5. Future dates (bad data)
SELECT *
FROM CUSTOMER_RAW
WHERE MODIFIEDDATE > CURRENT_TIMESTAMP();

-- 6. Empty account numbers
SELECT *
FROM CUSTOMER_RAW
WHERE TRIM(ACCOUNTNUMBER) = '' OR ACCOUNTNUMBER IS NULL;

-- 7. Sample data
SELECT *
FROM CUSTOMER_RAW
         LIMIT 20;