USE DATABASE SALES_DWH_DEV;
USE SCHEMA CONTROL;

CREATE OR REPLACE PROCEDURE SP_LOAD_PIPELINE(PIPELINE_NAME_ARG STRING)
    RETURNS STRING
    LANGUAGE SQL
AS
$$
DECLARE
    V_SOURCE_TABLE STRING;
    V_TARGET_TABLE STRING;
    V_LOAD_TYPE STRING;
    V_LOAD_MODE STRING;

    V_TARGET_COLUMNS STRING;
    V_SELECT_EXPRESSIONS STRING;
    V_SQL STRING;

    V_START_TIME TIMESTAMP_NTZ;
    V_END_TIME TIMESTAMP_NTZ;
    V_ROWS_LOADED NUMBER DEFAULT 0;
    V_RUN_ID NUMBER;

BEGIN
    V_START_TIME := CURRENT_TIMESTAMP();

    SELECT
        SOURCE_TABLE,
        TARGET_TABLE,
        LOAD_TYPE,
        LOAD_MODE
        INTO
        :V_SOURCE_TABLE,
        :V_TARGET_TABLE,
        :V_LOAD_TYPE,
        :V_LOAD_MODE
    FROM SALES_DWH_DEV.CONTROL.LOAD_CONFIG
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND ACTIVE_FLAG = TRUE;


    INSERT INTO SALES_DWH_DEV.CONTROL.PIPELINE_RUN_LOG (
        PIPELINE_NAME,
        SOURCE_TABLE,
        TARGET_TABLE,
        LOAD_TYPE,
        LOAD_MODE,
        STATUS,
        START_TIME
    )
    VALUES (
               :PIPELINE_NAME_ARG,
               :V_SOURCE_TABLE,
               :V_TARGET_TABLE,
               :V_LOAD_TYPE,
               :V_LOAD_MODE,
               'RUNNING',
               :V_START_TIME
           );

    SELECT MAX(RUN_ID)
        INTO :V_RUN_ID
    FROM SALES_DWH_DEV.CONTROL.PIPELINE_RUN_LOG
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND START_TIME = :V_START_TIME;

    SELECT LISTAGG(TARGET_COLUMN, ', ')
                   WITHIN GROUP (ORDER BY COLUMN_SEQUENCE)
        INTO :V_TARGET_COLUMNS
    FROM SALES_DWH_DEV.CONTROL.COLUMN_MAPPING
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND ACTIVE_FLAG = TRUE;

    SELECT LISTAGG(TRANSFORM_EXPRESSION || ' AS ' || TARGET_COLUMN, ', ')
                   WITHIN GROUP (ORDER BY COLUMN_SEQUENCE)
        INTO :V_SELECT_EXPRESSIONS
    FROM SALES_DWH_DEV.CONTROL.COLUMN_MAPPING
    WHERE PIPELINE_NAME = :PIPELINE_NAME_ARG
      AND ACTIVE_FLAG = TRUE;

    IF (V_LOAD_MODE = 'TRUNCATE_INSERT') THEN

        EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || V_TARGET_TABLE;

        V_SQL := 'INSERT INTO ' || V_TARGET_TABLE || ' (' ||
                 V_TARGET_COLUMNS || ') SELECT ' ||
                 V_SELECT_EXPRESSIONS || ' FROM ' || V_SOURCE_TABLE;

        EXECUTE IMMEDIATE V_SQL;

        V_ROWS_LOADED := SQLROWCOUNT;
        V_END_TIME := CURRENT_TIMESTAMP();

        UPDATE SALES_DWH_DEV.CONTROL.PIPELINE_RUN_LOG
        SET STATUS = 'SUCCESS',
            END_TIME = :V_END_TIME,
            ROWS_LOADED = :V_ROWS_LOADED,
            EXECUTED_SQL = :V_SQL
        WHERE RUN_ID = :V_RUN_ID;

        RETURN 'SUCCESS: PIPELINE ' || PIPELINE_NAME_ARG ||
               ' executed successfully. Rows loaded: ' || V_ROWS_LOADED;

    ELSE

        V_END_TIME := CURRENT_TIMESTAMP();

        UPDATE SALES_DWH_DEV.CONTROL.PIPELINE_RUN_LOG
        SET STATUS = 'FAILED',
            END_TIME = :V_END_TIME,
            ERROR_MESSAGE = 'Unsupported LOAD_MODE for V1 -> ' || COALESCE(V_LOAD_MODE, 'NULL')
        WHERE RUN_ID = :V_RUN_ID;

        RETURN 'ERROR: Unsupported LOAD_MODE for V1 -> ' || COALESCE(V_LOAD_MODE, 'NULL');

    END IF;

EXCEPTION
    WHEN OTHER THEN
        V_END_TIME := CURRENT_TIMESTAMP();

        UPDATE SALES_DWH_DEV.CONTROL.PIPELINE_RUN_LOG
        SET STATUS = 'FAILED',
            END_TIME = :V_END_TIME,
            ERROR_MESSAGE = 'Execution failed'
        WHERE RUN_ID = :V_RUN_ID;

        RETURN 'FAILED: Pipeline ' || PIPELINE_NAME_ARG;
END;
$$;