USE DATABASE SALES_DWH_DEV;
USE SCHEMA CONTROL;

-- CALL SALES_DWH_DEV.CONTROL.SP_LOAD_PIPELINE('LOAD_CUSTOMER');


CALL SP_LOAD_PIPELINE('LOAD_CUSTOMER');
CALL SP_LOAD_PIPELINE('LOAD_PRODUCT');
CALL SP_LOAD_PIPELINE('LOAD_SALES_DETAIL');
CALL SP_LOAD_PIPELINE('LOAD_SALES_HEADER');
