USE DATABASE SALES_DWH_DEV;
USE SCHEMA CONTROL;

TRUNCATE TABLE LOAD_CONFIG;
TRUNCATE TABLE  COLUMN_MAPPING;

COPY INTO LOAD_CONFIG
    (
     PIPELINE_NAME,
     SOURCE_TABLE,
     TARGET_TABLE,
     LOAD_TYPE,
     LOAD_MODE,
     ACTIVE_FLAG,
     PIPELINE_DESCRIPTION
        )
    FROM @METADATA_STAGE/load_config.csv;

COPY INTO COLUMN_MAPPING
    (
     PIPELINE_NAME,
     COLUMN_SEQUENCE,
     SOURCE_COLUMN,
     TARGET_COLUMN,
     TRANSFORM_EXPRESSION,
     ACTIVE_FLAG
        )
    FROM @METADATA_STAGE/column_mapping.csv;