name: Deploy to Snowflake Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

    steps:
      - uses: actions/checkout@v5

      - uses: snowflakedb/snowflake-cli-action@v2.0

      - name: Test Snowflake connection
        run: |
          snow connection test -x


      - name: Deploy setup objects
        run: |
          snow sql -x -f sql/00_setup/schemas.sql
          snow sql -x -f sql/00_setup/file_formats.sql
          snow sql -x -f sql/00_setup/stages.sql

      - name: Deploy bronze tables
        run: |
          snow sql -x -f sql/01_bronze/source_bronze.sql
          snow sql -x -f sql/01_bronze/validate_bronze_customer.sql

      - name: Deploy metadata tables and load metadata
        run: |
          snow sql -x -f sql/02-metadata/pipeline_run_log.sql
          snow sql -x -f sql/02-metadata/control_tables.sql
          snow sql -x -f sql/02-metadata/load_metadata.sql

      - name: Deploy silver tables
        run: |
          snow sql -x -f sql/03_silver/target_tables.sql

      - name: Deploy procedures
        run: |
          snow sql -x -f sql/04_procedures/sp_load_pipeline.sql

      - name: Run customer pipeline
        run: |
          snow sql -x -f sql/05_runs/run_customer_pipeline.sql

      - name: Validate silver customer
        run: |
          snow sql -x -f sql/06_validation/validate_silver_customer.sql